name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'

      - name: Install and build
        run: npm ci

      - name: Format-check
        run: npm run format -- --check

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test -- --coverage

      - name: Coverage
        uses: codecov/codecov-action@v7

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'

      - name: Install and build
        run: npm ci

      - name: Release
        uses: cycjimmy/semantic-release-action@v6
        with:
          extra_plugins: |
            conventional-changelog-conventionalcommits@9
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
